version: "3.9"

networks:
  marea-network:
    driver: bridge

services:
  supabase-mcp:
    build:
      context: .
      dockerfile: ./mcp_kit/servers/supabase/Dockerfile
    container_name: supabase-mcp-server
    restart: unless-stopped
    command: tail -f /dev/null
    networks: [marea-network]
  finance-mcp:
    build:
      context: .
      dockerfile: ./mcp_kit/servers/finance/Dockerfile
    container_name: finance-mcp-server
    restart: unless-stopped
    command: tail -f /dev/null
    networks: [marea-network]
  location-mcp:
    build:
      context: .
      dockerfile: ./mcp_kit/servers/location/Dockerfile
    container_name: location-mcp-server
    restart: unless-stopped
    command: tail -f /dev/null
    networks: [marea-network]

  marea:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marea-main
    depends_on:
      - supabase-mcp
      - finance-mcp
      - location-mcp
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    ports:
      - "8000:8000"
    command: python gradio_app.py
    restart: unless-stopped 
    networks: [marea-network]
    user: "0:0"